#  https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle#building-and-testing-your-code
name: ci

on:
  pull_request:
    branches:
      - main

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8' ]
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Unit tests
        run: ./gradlew test -PallScalaVersions
      - name: Integration tests
        run: ./gradlew integrationTest -PallScalaVersions
      - name: Build
        run: ./gradlew build -x test -PallScalaVersions
      - name: Report Code Coverage
        run: ./gradlew reportScoverage
      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/scoverage/cobertura.xml
          name: codecov-spark-filetransfer
