#  https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle#building-and-testing-your-code
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8' ]
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Unit tests
        run: ./gradlew test -PallScalaVersions
      - name: Archive Unit Test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: ./build/reports/tests/test
      - name: Integration tests
        run: ./gradlew integrationTest -PallScalaVersions
      - name: Archive Integration Test results
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-report
          path: ./build/reports/tests/integrationTest
      - name: Build
        run: ./gradlew build -xtest -PallScalaVersions
      - name: Report Code Coverage
        run: ./gradlew reportScoverage
      - name: Archive Code Coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./build/reports/scoverage
      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/scoverage/cobertura.xml
          name: codecov-spark-filetransfer
